### ISSUE TITLE
Release with topic exchange support

### ISSUE THREAD

**Issue by danielfarrell** [rentpath/bunny_mock#4]
Any chance you guys can push a point release with the topic exchange support?

**Comment by mpelzsherman** [comment]
Can you be more precise? 

We just made some improvements to the exchange support - hopefully these will be helpful for you. (?) We are publishing to our internal gem server only at this time, but you can try them out by pointing your Gemfile entry to github.

**Comment by danielfarrell** [comment]
You merged in my fix for topic exchange support a while back.  I was just
looking for a new release to rubygems.

**Comment by danielfarrell** [comment]
Thanks! :+1:
